pretzel: 
    engine: liquid

# Site settings
author: Paul Miller # name of the author
title: The gyrations of a pointless and uncaring universe  # site title
url: https://paulgmiller.github.io # site url
contact: paul.miller@gmail.com # mail of the author
google_analytics: UA-117157201-1