apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: album
  name: album
  namespace: album
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: album
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: album
    spec:
      containers:
      - env:
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: ACCESS_KEY_ID
              name: album
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_ACCESS_KEY
              name: album
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              key: SESSION_SECRET
              name: album
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: album
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AUTH_PASSWORD
              name: album
        - name: BASE_PATH
          value: /album
        - name: BLOG_TIMEZONE
          value: America/Los_Angeles
        - name: COOKIE_SECURE
          value: "true"
        - name: GITHUB_BASE_BRANCH
          value: master
        - name: GITHUB_OWNER
          value: paulgmiller
        - name: GITHUB_REPO
          value: paulgmiller.github.io
        - name: ALLOWED_EMAIL
          value: paul.miller@gmail.com
        image: paulgmiller/album:df617a9
        imagePullPolicy: IfNotPresent
        name: album
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-07T20:05:44Z"
    lastUpdateTime: "2025-04-07T20:05:48Z"
    message: ReplicaSet "album-c74486c7c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-07T20:05:49Z"
    lastUpdateTime: "2025-04-07T20:05:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
